# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e63da4d75d0391e83de70e49a940b8192d3399e7e00abdeaf53c946a1cf6969dfc192a80cc67432be398f62aaf63b4d2be53afba3085b7f5ca22d4b93f945954

test:
  secret_key_base: 0824213286d37237dd992117d3c75f7d1faefd8737d55a173f3f3e24b6eb5db9f18f2ccaf43cad332fdd09fc5d111388af68cd58bcf88cc98af3e0618a019e13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
